services:
  app:
    build: .
    container_name: backend
    working_dir: /backend
    environment:
      - TZ=UTC
      - PORT=3333
      - HOST=0.0.0.0
      - LOG_LEVEL=info
      - APP_KEY=pRD45ao_jypGcua3fws9iD8IzknoxCKj
      - NODE_ENV=development
      - DB_HOST=127.0.0.1
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_DATABASE=bemobiledb
    ports:
      - "3333:3333"
    healthcheck:
      test: ['CMD', 'lsof', '-t', '-i:3333']
      timeout: 10s
      retries: 5
    depends_on:
      mysql_db:
        condition: service_healthy
    networks:
      - backend_network

  mysql_db:
    image: mysql:8.0
    restart: always
    container_name: mysql_db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bemobiledb
    ports:
      - "3306:3306"
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 10s
      retries: 5
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge

volumes:
  mysql_data:
